use crate::graph::Graph;
use crate::parser::{Block, Page};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::fs;
use std::path::Path;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExportConfig {
    pub theme: String,
    pub include_backlinks: bool,
    pub include_graph_view: bool,
    pub custom_css: Option<String>,
}

impl Default for ExportConfig {
    fn default() -> Self {
        Self {
            theme: "light".to_string(),
            include_backlinks: true,
            include_graph_view: false,
            custom_css: None,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PageMetadata {
    pub slug: String,
    pub title: String,
    pub properties: HashMap<String, String>,
    pub tags: Vec<String>,
    pub links: Vec<String>,
    pub backlinks: Vec<String>,
    pub content_url: String,
    pub block_count: usize,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct PageContent {
    pub slug: String,
    pub title: String,
    pub blocks: Vec<Block>,
}

/// Extract metadata from a page
pub fn extract_metadata(page: &Page, backlinks: &[String]) -> PageMetadata {
    let slug = page.title.to_lowercase().replace(' ', "-");
    let block_count = crate::parser::count_blocks(&page.blocks);

    PageMetadata {
        slug: slug.clone(),
        title: page.title.clone(),
        properties: page.properties.clone(),
        tags: page.tags.clone(),
        links: page.links.clone(),
        backlinks: backlinks.to_vec(),
        content_url: format!("content/{}.json", slug),
        block_count,
    }
}

/// Export graph to HTML (for WASM compatibility)
pub fn export_to_html(graph: &Graph, config: &ExportConfig) -> Result<String, String> {
    let metadata: Vec<_> = graph
        .pages()
        .map(|page| {
            let backlinks = graph.get_backlinks(&page.path);
            extract_metadata(page, &backlinks)
        })
        .collect();

    generate_index_html(&metadata, config)
}

/// Generate index.html with navigation and search
pub fn generate_index_html(metadata: &[PageMetadata], _config: &ExportConfig) -> Result<String, String> {
    let mut html = String::from("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n");
    html.push_str("<meta charset=\"UTF-8\">\n");
    html.push_str("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
    html.push_str("<title>Logseq Published Graph</title>\n");
    html.push_str("<link rel=\"stylesheet\" href=\"style.css\">\n");
    html.push_str("</head>\n<body>\n");

    html.push_str("<div class=\"container\">\n");
    html.push_str("<header>\n");
    html.push_str("<h1>📚 Logseq Knowledge Graph</h1>\n");
    html.push_str(&format!("<p class=\"stats\">{} pages published</p>\n", metadata.len()));
    html.push_str("</header>\n");

    // Search box
    html.push_str("<div class=\"search-box\">\n");
    html.push_str("<input type=\"text\" id=\"search\" placeholder=\"Search pages...\" />\n");
    html.push_str("</div>\n");

    html.push_str("<main>\n");
    html.push_str("<div id=\"page-list\">\n");

    let mut sorted_metadata = metadata.to_vec();
    sorted_metadata.sort_by(|a, b| a.title.cmp(&b.title));

    for meta in sorted_metadata {
        html.push_str(&format!(
            "<div class=\"page-card\" data-slug=\"{}\" data-tags=\"{}\">\n",
            escape_html(&meta.slug),
            escape_html(&meta.tags.join(" "))
        ));
        html.push_str(&format!("<h3>{}</h3>\n", escape_html(&meta.title)));

        if !meta.tags.is_empty() {
            html.push_str("<div class=\"tags\">\n");
            for tag in &meta.tags {
                html.push_str(&format!("<span class=\"tag\">#{}</span>", escape_html(tag)));
            }
            html.push_str("</div>\n");
        }

        html.push_str(&format!(
            "<p class=\"meta\">{} blocks • {} links • {} backlinks</p>\n",
            meta.block_count, meta.links.len(), meta.backlinks.len()
        ));
        html.push_str("</div>\n");
    }

    html.push_str("</div>\n");
    html.push_str("<div id=\"page-content\" style=\"display:none;\"></div>\n");
    html.push_str("</main>\n");

    html.push_str("<footer>\n");
    html.push_str("<p>Generated by Logseq Publisher (Rust) • Built with ❤️ and 🦀</p>\n");
    html.push_str("</footer>\n");
    html.push_str("</div>\n");

    // Embed metadata JSON
    html.push_str("<script id=\"pages-data\" type=\"application/json\">\n");
    html.push_str(&serde_json::to_string(metadata).map_err(|e| e.to_string())?);
    html.push_str("\n</script>\n");

    html.push_str("<script src=\"app.js\"></script>\n");
    html.push_str("</body>\n</html>");

    Ok(html)
}

/// Export page content as JSON
pub fn export_page_content(page: &Page, output_dir: &Path) -> Result<(), String> {
    let slug = page.title.to_lowercase().replace(' ', "-");
    let content = PageContent {
        slug: slug.clone(),
        title: page.title.clone(),
        blocks: page.blocks.clone(),
    };

    let content_dir = output_dir.join("content");
    fs::create_dir_all(&content_dir).map_err(|e| format!("Failed to create content dir: {}", e))?;

    let file_path = content_dir.join(format!("{}.json", slug));
    let json = serde_json::to_string_pretty(&content).map_err(|e| e.to_string())?;

    fs::write(file_path, json).map_err(|e| format!("Failed to write content file: {}", e))?;

    Ok(())
}

/// Generate search index JSON
pub fn generate_search_index(metadata: &[PageMetadata]) -> String {
    let mut index = Vec::new();

    for meta in metadata {
        index.push(serde_json::json!({
            "slug": meta.slug,
            "title": meta.title,
            "tags": meta.tags,
            "links": meta.links,
        }));
    }

    serde_json::to_string_pretty(&index).unwrap_or_else(|_| "[]".to_string())
}

/// Generate CSS file
pub fn generate_css(config: &ExportConfig) -> String {
    let mut css = String::from(r#"/* Logseq Publisher Styles */

:root {
    --bg-color: #ffffff;
    --text-color: #2d3748;
    --link-color: #3182ce;
    --border-color: #e2e8f0;
    --tag-bg: #edf2f7;
    --block-border: #cbd5e0;
    --card-bg: #f7fafc;
}

* {
    box-sizing: border-box;
    margin: 0;
    padding: 0;
}

body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
    line-height: 1.6;
    color: var(--text-color);
    background: var(--bg-color);
}

.container {
    max-width: 1200px;
    margin: 0 auto;
    padding: 2rem;
}

header {
    margin-bottom: 3rem;
    padding-bottom: 1rem;
    border-bottom: 2px solid var(--border-color);
}

h1 {
    font-size: 2.5rem;
    margin-bottom: 0.5rem;
}

h2 {
    font-size: 1.8rem;
    margin: 1.5rem 0 1rem;
}

h3 {
    font-size: 1.3rem;
    margin-bottom: 0.5rem;
}

.stats {
    color: #718096;
    font-size: 1rem;
}

.search-box {
    margin-bottom: 2rem;
}

.search-box input {
    width: 100%;
    padding: 0.75rem 1rem;
    font-size: 1rem;
    border: 2px solid var(--border-color);
    border-radius: 0.5rem;
    outline: none;
    transition: border-color 0.2s;
}

.search-box input:focus {
    border-color: var(--link-color);
}

#page-list {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
    gap: 1.5rem;
}

.page-card {
    background: var(--card-bg);
    padding: 1.5rem;
    border-radius: 0.5rem;
    border: 1px solid var(--border-color);
    cursor: pointer;
    transition: transform 0.2s, box-shadow 0.2s;
}

.page-card:hover {
    transform: translateY(-2px);
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
}

.page-card h3 {
    color: var(--link-color);
}

.tags {
    margin: 0.75rem 0;
}

.tag {
    background: var(--tag-bg);
    padding: 0.25rem 0.5rem;
    border-radius: 0.25rem;
    font-size: 0.875rem;
    margin-right: 0.5rem;
    display: inline-block;
}

.meta {
    color: #718096;
    font-size: 0.875rem;
    margin-top: 0.5rem;
}

#page-content {
    margin-top: 2rem;
    padding-top: 2rem;
    border-top: 2px solid var(--border-color);
}

.block {
    margin: 0.75rem 0;
    padding-left: 1.5rem;
    position: relative;
}

.block::before {
    content: "•";
    position: absolute;
    left: 0;
    color: var(--link-color);
    font-weight: bold;
}

.block-content {
    padding: 0.25rem 0;
}

.block-children {
    margin-left: 1.5rem;
    border-left: 2px solid var(--block-border);
    padding-left: 1rem;
}

.wiki-link {
    color: var(--link-color);
    text-decoration: none;
    border-bottom: 1px dotted var(--link-color);
    cursor: pointer;
}

.wiki-link:hover {
    background: #ebf8ff;
    border-bottom-style: solid;
}

.properties {
    background: var(--card-bg);
    padding: 1rem;
    border-radius: 0.5rem;
    margin: 1rem 0;
    font-size: 0.875rem;
}

.backlinks {
    margin-top: 3rem;
    padding-top: 2rem;
    border-top: 2px solid var(--border-color);
}

.backlinks ul {
    list-style: none;
    padding: 0;
}

.backlinks li {
    margin: 0.5rem 0;
}

code {
    background: var(--card-bg);
    padding: 0.125rem 0.375rem;
    border-radius: 0.25rem;
    font-family: 'Monaco', 'Courier New', monospace;
    font-size: 0.875rem;
}

pre {
    background: var(--card-bg);
    padding: 1rem;
    border-radius: 0.5rem;
    overflow-x: auto;
    margin: 1rem 0;
}

footer {
    margin-top: 3rem;
    padding-top: 2rem;
    border-top: 1px solid var(--border-color);
    text-align: center;
    color: #718096;
    font-size: 0.875rem;
}

"#);

    if let Some(custom_css) = &config.custom_css {
        css.push('\n');
        css.push_str(custom_css);
    }

    css
}

/// Generate JavaScript file
pub fn generate_js(_config: &ExportConfig) -> String {
    String::from(r##"// Logseq Publisher JavaScript

const pagesData = JSON.parse(document.getElementById('pages-data').textContent);
let currentPage = null;

// Search functionality
const searchInput = document.getElementById('search');
if (searchInput) {
    searchInput.addEventListener('input', (e) => {
        const query = e.target.value.toLowerCase();
        const cards = document.querySelectorAll('.page-card');

        cards.forEach(card => {
            const title = card.querySelector('h3').textContent.toLowerCase();
            const tags = card.dataset.tags.toLowerCase();

            if (title.includes(query) || tags.includes(query)) {
                card.style.display = 'block';
            } else {
                card.style.display = 'none';
            }
        });
    });
}

// Page card click handlers
document.querySelectorAll('.page-card').forEach(card => {
    card.addEventListener('click', () => {
        const slug = card.dataset.slug;
        loadPage(slug);
    });
});

async function loadPage(slug) {
    const pageData = pagesData.find(p => p.slug === slug);
    if (!pageData) return;

    try {
        const response = await fetch(pageData.content_url);
        const content = await response.json();

        displayPage(content, pageData);
    } catch (err) {
        console.error('Failed to load page:', err);
    }
}

function displayPage(content, metadata) {
    const pageContent = document.getElementById('page-content');
    const pageList = document.getElementById('page-list');

    pageList.style.display = 'none';
    pageContent.style.display = 'block';

    let html = '<button id="back-btn">← Back to all pages</button>\n';
    html += `<article>\n`;
    html += `<h1>${escapeHtml(content.title)}</h1>\n`;

    if (metadata.tags.length > 0) {
        html += '<div class="tags">\n';
        metadata.tags.forEach(tag => {
            html += `<span class="tag">#${escapeHtml(tag)}</span>`;
        });
        html += '</div>\n';
    }

    html += '<div class="blocks">\n';
    content.blocks.forEach(block => {
        html += renderBlock(block);
    });
    html += '</div>\n';

    if (metadata.backlinks.length > 0) {
        html += '<div class="backlinks">\n';
        html += '<h2>📎 Linked References</h2>\n';
        html += '<ul>\n';
        metadata.backlinks.forEach(backlink => {
            const backlinkMeta = pagesData.find(p => p.slug === backlink);
            if (backlinkMeta) {
                html += `<li><a href="#" class="backlink" data-slug="${backlink}">${escapeHtml(backlinkMeta.title)}</a></li>\n`;
            }
        });
        html += '</ul>\n';
        html += '</div>\n';
    }

    html += '</article>\n';

    pageContent.innerHTML = html;

    // Add back button handler
    document.getElementById('back-btn').addEventListener('click', () => {
        pageContent.style.display = 'none';
        pageList.style.display = 'grid';
    });

    // Add backlink click handlers
    document.querySelectorAll('.backlink').forEach(link => {
        link.addEventListener('click', (e) => {
            e.preventDefault();
            loadPage(link.dataset.slug);
        });
    });

    // Add wiki-link handlers
    document.querySelectorAll('.wiki-link').forEach(link => {
        link.addEventListener('click', (e) => {
            e.preventDefault();
            const targetSlug = link.dataset.slug;
            if (targetSlug) {
                loadPage(targetSlug);
            }
        });
    });
}

function renderBlock(block) {
    let html = `<div class="block" data-id="${escapeHtml(block.id)}">\n`;
    html += `<div class="block-content">${renderMarkdown(block.content)}</div>\n`;

    if (block.children && block.children.length > 0) {
        html += '<div class="block-children">\n';
        block.children.forEach(child => {
            html += renderBlock(child);
        });
        html += '</div>\n';
    }

    html += '</div>\n';
    return html;
}

function renderMarkdown(content) {
    let result = escapeHtml(content);

    // Wiki-links [[page]]
    result = result.replace(/\[\[([^\]|]+)(?:\|([^\]]+))?\]\]/g, (match, link, alias) => {
        const displayText = alias || link;
        const slug = link.toLowerCase().replace(/\s+/g, '-');
        return `<a href="#" class="wiki-link" data-slug="${slug}">${displayText}</a>`;
    });

    // Tags #tag
    result = result.replace(/#([\w-]+)/g, '<span class="tag">#$1</span>');

    // Bold **text**
    result = result.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>');

    // Italic *text*
    result = result.replace(/\*([^*]+)\*/g, '<em>$1</em>');

    // Code `code`
    result = result.replace(/`([^`]+)`/g, '<code>$1</code>');

    return result;
}

function escapeHtml(text) {
    const div = document.createElement('div');
    div.textContent = text;
    return div.innerHTML;
}

console.log('Logseq Publisher initialized - ' + pagesData.length + ' pages loaded');
"##)
}

fn escape_html(s: &str) -> String {
    s.chars()
        .map(|c| match c {
            '<' => "&lt;".to_string(),
            '>' => "&gt;".to_string(),
            '&' => "&amp;".to_string(),
            '"' => "&quot;".to_string(),
            '\'' => "&#x27;".to_string(),
            _ => c.to_string(),
        })
        .collect()
}

/// Export a single page to HTML (for CLI usage)
pub fn export_page_to_html(page: &Page, backlinks: &[String], config: &ExportConfig) -> String {
    let mut html = String::new();

    html.push_str(&format!("<h1>{}</h1>\n", escape_html(&page.title)));

    if !page.tags.is_empty() {
        html.push_str("<div class=\"tags\">\n");
        for tag in &page.tags {
            html.push_str(&format!("<span class=\"tag\">#{}</span>", escape_html(tag)));
        }
        html.push_str("</div>\n");
    }

    if !page.properties.is_empty() {
        html.push_str("<div class=\"properties\">\n<h3>Properties</h3>\n<ul>\n");
        for (key, value) in &page.properties {
            html.push_str(&format!(
                "<li><strong>{}:</strong> {}</li>\n",
                escape_html(key),
                escape_html(value)
            ));
        }
        html.push_str("</ul>\n</div>\n");
    }

    html.push_str("<div class=\"blocks\">\n");
    for block in &page.blocks {
        html.push_str(&render_block_html(block));
    }
    html.push_str("</div>\n");

    if config.include_backlinks && !backlinks.is_empty() {
        html.push_str("<div class=\"backlinks\">\n<h2>Backlinks</h2>\n<ul>\n");
        for backlink in backlinks {
            html.push_str(&format!(
                "<li><a href=\"#\">{}</a></li>\n",
                escape_html(backlink)
            ));
        }
        html.push_str("</ul>\n</div>\n");
    }

    html
}

fn render_block_html(block: &Block) -> String {
    let mut html = format!(
        "<div class=\"block\" data-id=\"{}\">\n<div class=\"block-content\">{}</div>\n",
        escape_html(&block.id),
        escape_html(&block.content)
    );

    if !block.children.is_empty() {
        html.push_str("<div class=\"block-children\">\n");
        for child in &block.children {
            html.push_str(&render_block_html(child));
        }
        html.push_str("</div>\n");
    }

    html.push_str("</div>\n");
    html
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_escape_html() {
        assert_eq!(escape_html("<script>"), "&lt;script&gt;");
        assert_eq!(escape_html("A & B"), "A &amp; B");
    }

    #[test]
    fn test_export_config_default() {
        let config = ExportConfig::default();
        assert_eq!(config.theme, "light");
        assert!(config.include_backlinks);
    }
}
