/* auto-generated by NAPI-RS */

export interface ExportResult {
  pagesCount: number;
  ontologyCount: number;
  outputDir: string;
}

export interface OntologyStatsJS {
  classCount: number;
  propertyCount: number;
  namespaceCount: number;
  title: string;
  version: string;
}

/**
 * Export unified knowledge graph with pages and ontology
 * @param pagesDir - Directory containing Logseq pages
 * @param outputDir - Output directory for exported files
 * @returns ExportResult with counts and output path
 */
export function exportUnifiedGraph(pagesDir: string, outputDir: string): ExportResult;

/**
 * Load and get statistics from an ontology file
 * @param ontologyPath - Path to ontology JSON file
 * @returns OntologyStatsJS with statistics
 */
export function getOntologyStatistics(ontologyPath: string): OntologyStatsJS;

/**
 * Export ontology to JSON format
 * @param inputPath - Input ontology file path
 * @param outputPath - Output ontology file path
 * @returns OntologyStatsJS with statistics
 */
export function exportOntologyJson(inputPath: string, outputPath: string): OntologyStatsJS;

/**
 * Get the version of logseq-publisher
 * @returns Version string
 */
export function getVersion(): string;
